# general
background = '#1e1e2e'
border_fg = '#45475a'
text_fg = '#cdd6f4'
dimmed_text_fg = '#6c7086'
# input
input_text_fg = '#89dceb'
result_count_fg = '#89dceb'
# results
result_name_fg = '#89b4fa'
result_line_number_fg = '#f9e2af'
result_value_fg = '#b4befe'
selection_fg = '#a6e3a1'
selection_bg = '#313244'
match_fg = '#a6e3a1'
# preview
preview_title_fg = '#89dceb'
# modes
channel_mode_fg = '#1e1e2e'
channel_mode_bg = '#89dceb'
remote_control_mode_fg = '#1e1e2e'
remote_control_mode_bg = '#a6e3a1'