
# locations to be backed up to the cloud.

[thunderbird_windows]
path_local = '~/AppData/Roaming/Thunderbird/Profiles'
encrypt = true
zip = true
rel2home = true
os_specific = true
os = 'windows'


[thunderbird_linux]
path_local = '~/.thunderbird'
encrypt = true
zip = true
rel2home = true
os_specific = true
os = 'linux'


[zoxide_windows]
path_local = '~/AppData/Local/zoxide/db.zo'
encrypt = false
zip = false
rel2home = true
os_specific = true
os = 'windows'


[zoxide_linux]
path_local = '~/.local/share/zoxide/db.zo'
encrypt = false
zip = false
rel2home = true
os_specific = true
os = 'linux'

[atuin]
path_local = '~/.local/share/atuin/history.db'
encrypt = true
zip = false
rel2home = true
os_specific = false
os = 'any'


[bash_history]
path_local = '~/.bash_history'
encrypt = true
zip = false
rel2home = true
os_specific = true
os = 'linux'

[zsh_history]
path_local = '~/.zsh_history'
encrypt = true
zip = false
rel2home = true
os_specific = true
os = 'darwin'

[pwsh_history]
path_local = '~/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadLine/ConsoleHost_history.txt'
encrypt = true
zip = false
rel2home = true
os_specific = true
os = 'windows'


#[dotfiles]
# path_local = '~/dotfiles'
# encrypt = true
# zip = true
# rel2home = true
# os_specific = true


[ipython]
path_local = '~/.ipython'
encrypt = true
zip = true
rel2home = true
os_specific = false
os = 'any'
