
# directories to be added to PATH within shell profile.

[path_windows]
extension = ['~/code/machineconfig/src/machineconfig/scripts/windows',
             '~/dotfiles/scripts/windows',
             'C:\Program Files (x86)\GnuWin32\bin',
             'C:\Program Files\CodeBlocks\MinGW\bin',
             'C:\Program Files\nu\bin',
             'C:\Program Files\Graphviz\bin',  # required by .viz_object_hirarchy()
             ]


[path_linux]
extension = ['~/.local/bin',  # many apps, like rust-analyzer and lunarvim place their binaries here which is not in PATH by default
             '~/code/machineconfig/src/machineconfig/scripts/linux',
             '~/dotfiles/scripts/linux',
             '~/.nix-profile/bin',
             '/usr/games'
             ]
