

# =================== PRIVATE ================================
# os can be 'windows', 'linux,darwin', 'darwin' or 'any'

[git]
gitconfig = {original = '~/.gitconfig', self_managed = '~/dotfiles/creds/git/.gitconfig', os = 'any'}
gitcred = {original = '~/.git-credentials', self_managed = '~/dotfiles/creds/git/.git-credentials', os = 'any'}

[ssh]
keys = {original = '~/.ssh', self_managed = '~/dotfiles/creds/.ssh', contents = true, os = 'any'}

[gpg]
keys = {original = '~/.gnupg', self_managed = '~/dotfiles/creds/.gnupg', contents = true, os = 'any'}

[pypi]
creds = {original = '~/.pypirc', self_managed = '~/dotfiles/creds/msc/.pypirc', os = 'any'}

[rclone]
config_xdg = {original = '~/.config/rclone/rclone.conf', self_managed = '~/dotfiles/creds/rclone/rclone.conf', os = 'linux,darwin'}
config_windows = {original = '~/AppData/Roaming/rclone/rclone.conf', self_managed = '~/dotfiles/creds/rclone/rclone.conf', os = 'windows'}

[cloudflare]
config = {original = '~/.cloudflared', self_managed = '~/dotfiles/creds/cloudflare/.cloudflared', os = 'any'}

[ngrok]
config_linux = {original = '~/.config/ngrok/ngrok.yml', self_managed = '~/dotfiles/creds/tokens/ngrok.yml', os = 'linux,darwin'}
config_windows = {original = '~/AppData/Local/ngrok/ngrok.yml', self_managed = '~/dotfiles/creds/tokens/ngrok.yml', os = 'windows'}

[m365]
config1 = {original = '~/.cli-m365-msal.json',            self_managed = '~/dotfiles/creds/tokens/.cli-m365-msal.json', os = 'any'}
config2 = {original = '~/.cli-m365-all-connections.json', self_managed = '~/dotfiles/creds/tokens/.cli-m365-all-connections.json', os = 'any'}
config3 = {original = '~/.cli-m365-connection.json',      self_managed = '~/dotfiles/creds/tokens/.cli-m365-connection.json', os = 'any'}
# config2 = {original = '~/.cli-m365-tokens.json',        self_managed = '~/dotfiles/creds/tokens/.cli-m365-tokens.json'}

[remmina]
data = {original = '~/.var/app/org.remmina.Remmina/data/remmina', self_managed = '~/dotfiles/creds/RDP/remmina/data/remmina', os = 'any'}

[webapp_linux]
brave = {original = '~/.local/share/applications', self_managed = '~/dotfiles/config/webapps/linux/brave', contents = true, os = 'linux,darwin'}

# [startup_windows]
# startup = {original = '~/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup', self_managed = '~/dotfiles/scripts/windows_startup', contents = true}

# [aws]
# config = {original = '~/.aws/config', self_managed = '~/dotfiles/aws/.aws', contents = true}

[wt_windows]
settings = { original = '~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json', self_managed = 'CONFIG_ROOT/settings/shells/wt/settings.json' , os = 'windows'}


# =================== LLMs ============================

[chatgpt]
config = { original = '~/.config/chatgpt/config.json', self_managed = '~/dotfiles/creds/llm/chatgpt_cli/config.json' , os = 'any'}

[mods]
config = {original = '~/.config/mods/mods.yml', self_managed = '~/dotfiles/creds/llm/mods_cli/mods.yml', os = 'any'}

[github_cli_token]
token = {original = '~/.copilot-cli-access-token', self_managed = '~/dotfiles/creds/llm/github_cli/.copilot-cli-access-token', os = 'any'}

[aider]
config = {original = '~/.aider.conf.yml', self_managed = '~/dotfiles/creds/llm/aider/.aider.conf.yml', os = 'any'}

[marvin]
config = {original = '~/.marvin/.env', self_managed = '~/dotfiles/creds/llm/marvin/.env', os = 'any'}
threads = {original = '~/.marvin/cli/threads/default.json', self_managed = '~/dotfiles/creds/llm/marvin/threads/default.json', os = 'any'}

[docker]
config = {original = '~/.docker/config.json', self_managed = '~/dotfiles/creds/docker/config.json', os = 'any'}


# =========================== PUBLIC ======================================

[marimo]
config = {original = '~/.config/marimo/marimo.toml', self_managed = 'CONFIG_ROOT/settings/marimo/marimo.toml', os = 'any'}

[presenterm]
config = {original = '~/.config/presenterm/config.yaml', self_managed = 'CONFIG_ROOT/settings/presenterm/config.yaml', os = 'any'}

[keras]
config = {original = '~/.keras/keras.json', self_managed = 'CONFIG_ROOT/settings/keras/keras.json', os = 'any'}

# [streamlit]
# config = {original = '~/.streamlit/config.toml', self_managed = 'CONFIG_ROOT/settings/streamlit/config.toml'}

[procs]
config = {original = '~/.procs.toml', self_managed = 'CONFIG_ROOT/settings/procs/.procs.toml', os = 'any'}
config_again = {original = '~/.config/procs/config.toml', self_managed = 'CONFIG_ROOT/settings/procs/.procs.toml', os = 'any'}

[rofi_linux]
config = {original = '~/.config/rofi/config.rasi', self_managed = 'CONFIG_ROOT/settings/rofi/config.rasi', os = 'linux,darwin'}

[yazi]
yazi_windows = {original = '~/AppData/Roaming/yazi/config/yazi.toml', self_managed = 'CONFIG_ROOT/settings/yazi/yazi_windows.toml', os = 'windows'}
keymap_windows = {original = '~/AppData/Roaming/yazi/config/keymap.toml', self_managed = 'CONFIG_ROOT/settings/yazi/keymap_windows.toml', os = 'windows'}
theme_windows = {original = '~/AppData/Roaming/yazi/config/theme.toml', self_managed = 'CONFIG_ROOT/settings/yazi/theme.toml', os = 'windows'}
init_windows = {original = '~/AppData/Roaming/yazi/config/init.lua', self_managed = 'CONFIG_ROOT/settings/yazi/init.lua', os = 'windows'}
yazi_linux = {original = '~/.config/yazi/yazi.toml', self_managed = 'CONFIG_ROOT/settings/yazi/yazi_linux.toml', os = 'linux,darwin'}
keymap_linux = {original = '~/.config/yazi/keymap.toml', self_managed = 'CONFIG_ROOT/settings/yazi/keymap_linux.toml', os = 'linux,darwin'}
theme_linux = {original = '~/.config/yazi/theme.toml', self_managed = 'CONFIG_ROOT/settings/yazi/theme.toml', os = 'linux,darwin'}
init_linux = {original = '~/.config/yazi/init.lua', self_managed = 'CONFIG_ROOT/settings/yazi/init.lua', os = 'linux,darwin'}
yazi_picker_linux = { original = '~/.config/helix/yazi-picker.sh', self_managed = 'CONFIG_ROOT/settings/helix/yazi-picker.sh' , os = 'linux,darwin'}

[television]
cable_linux = {original = '~/.config/television/cable', self_managed = 'CONFIG_ROOT/settings/television/cable_unix', contents = true, os = 'linux,darwin'}
cable_windows = {original = '~/AppData/Local/television/config/cable', self_managed = 'CONFIG_ROOT/settings/television/cable_windows', contents = true, os = 'windows'}

[tv]
config_linux = {original = '~/.config/television/config.toml', self_managed = 'CONFIG_ROOT/settings/tv/config.toml', os = 'linux,darwin'}
themes_linux = {original = '~/.config/television/themes', self_managed = 'CONFIG_ROOT/settings/tv/themes', contents = true, os = 'linux,darwin'}
config_windows = {original = '~/AppData/Local/television/config.toml', self_managed = 'CONFIG_ROOT/settings/tv/config.toml', os = 'windows'}
themes_windows = {original = '~/AppData/Local/television/themes', self_managed = 'CONFIG_ROOT/settings/tv/themes', contents = true, os = 'windows'}

[lf]
config_windows = {original = '~/AppData/Local/lf/lfrc', self_managed = 'CONFIG_ROOT/settings/lf/windows/lfrc', os = 'windows'}
colors_windows = {original = '~/AppData/Local/lf/colors', self_managed = 'CONFIG_ROOT/settings/lf/windows/colors', os = 'windows'}
icons_windows = {original = '~/AppData/Local/lf/icons', self_managed = 'CONFIG_ROOT/settings/lf/windows/icons', os = 'windows'}
config_linux = {original = '~/.config/lf/lfrc', self_managed = 'CONFIG_ROOT/settings/lf/linux/lfrc', os = 'linux,darwin'}
colors_linux = {original = '~/.config/lf/colors', self_managed = 'CONFIG_ROOT/settings/lf/linux/colors', os = 'linux,darwin'}
icons_linux = {original = '~/.config/lf/icons', self_managed = 'CONFIG_ROOT/settings/lf/linux/icons', os = 'linux,darwin'}

[broot]
config = {original = '~/.config/broot/conf.toml', self_managed = 'CONFIG_ROOT/settings/broot/conf.toml', os = 'any'}

[pistol_linux]
config = {original = '~/.config/pistol/pistol.conf', self_managed = 'CONFIG_ROOT/settings/pistol/pistol.conf', os = 'linux,darwin'}

[glow]
config = {original = '~/.config/glow/glow.yml', self_managed = 'CONFIG_ROOT/settings/glow/glow.yml', os = 'any'}

[gromit_linux]
config = {original = '~/.var/app/net.christianbeier.Gromit-MPX/config/gromit-mpx.cfg', self_managed = 'CONFIG_ROOT/settings/gromit-mpx/gromit-mpx.cfg', copy = true, os = 'linux,darwin'}


#[broot_windows]
#config = { original = '~/AppData/Roaming/dystroy/config', self_managed = 'CONFIG_ROOT/settings/broot/config' }

[starship]
config = {original = '~/.config/starship.toml', self_managed = 'CONFIG_ROOT/settings/shells/starship/starship.toml', os = 'any'}


[kanata]
config = {original = '~/.config/kanata/kanata.kbd', self_managed = 'CONFIG_ROOT/settings/keyboard/kanata/kanata.kbd', os = 'any'}

[espanso]
config = {original = '~/.config/espanso/config/default.yml', self_managed = 'CONFIG_ROOT/settings/keyboard/espanso/config/default.yml', os = 'any'}
match = {original = '~/.config/espanso/match/base.yml', self_managed = 'CONFIG_ROOT/settings/keyboard/espanso/match/base.yml', copy = true, os = 'any'}


[pudb]
config = {original = '~/.config/pudb/pudb.cfg', self_managed = 'CONFIG_ROOT/settings/pudb/pudb.cfg', os = 'any'}


# ============================= shells profiles ==================================

# [powershell_windows]
# CurrentUserCurrentHost = {original = '~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1', self_managed = '~/dotfiles/shells/windows_powershell/CurrentUserCurrentHost/Microsoft.PowerShell_profile.ps1'}
# CurrentUserAllHosts = {original = '~/Documents/WindowsPowerShell/profile.ps1', self_managed = '~/dotfiles/shells/windows_powershell/AllUsersCurrentHost/profile.ps1'}
# AllUsersCurrentHost = {original = 'C:/Windows/System32/WindowsPowerShell/v1.0/Microsoft.PowerShell_profile.ps1', self_managed = '~/dotfiles/shells/powershell/AllUsersCurrentHost/Microsoft.PowerShell_profile.ps1'}
# AllUsersAllHosts = {original = 'C:/Windows/System32/WindowsPowerShell/v1.0/profile.ps1', self_managed = '~/dotfiles/shells/windows_powershell/AllUsersAllHosts/profile.ps1'}

# [pwsh_windows]
# CurrentUserCurrentHost = {original = '~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1', self_managed = 'CONFIG_ROOT/settings/shells/pwsh/init.ps1'}
# CurrentUserAllHosts = {original = '~/Documents/PowerShell/profile.ps1', self_managed = 'CONFIG_ROOT/settings/shells/pwsh/profile.ps1'}
# AllUsersCurrentHost = {original = 'C:/Program Files/PowerShell/7/Microsoft.PowerShell_profile.ps1', self_managed = 'CONFIG_ROOT/settings/shells/pwsh/init.ps1'}
# AllUsersAllHosts = {original = 'C:/Program Files/PowerShell/7/profile.ps1', self_managed = 'CONFIG_ROOT/settings/shells/pwsh/init.ps1'}


[nushell]
config_windows = {original = '~/AppData/Roaming/nushell/config.nu', self_managed = 'CONFIG_ROOT/settings/shells/nushell/config.nu', os = 'windows'}
env_windows = {original = '~/AppData/Roaming/nushell/env.nu', self_managed = 'CONFIG_ROOT/settings/shells/nushell/env.nu', os = 'windows'}
config_linux = {original = '~/.config/nushell/config.nu', self_managed = 'CONFIG_ROOT/settings/shells/nushell/config.nu', os = 'linux,darwin'}
env_linux = {original = '~/.config/nushell/env.nu', self_managed = 'CONFIG_ROOT/settings/shells/nushell/env.nu', os = 'linux,darwin'}

[kitty_linux]
config = {original = '~/.config/kitty/kitty.conf', self_managed = 'CONFIG_ROOT/settings/shells/kitty/kitty.conf', os = 'linux,darwin'}

[alacritty]
config_linux = {original = '~/.config/alacritty/alacritty.toml', self_managed = 'CONFIG_ROOT/settings/shells/alacritty/alacritty.toml', os = 'linux,darwin'}
config_yaml_linux = {original = '~/.config/alacritty/alacritty.yml', self_managed = 'CONFIG_ROOT/settings/shells/alacritty/alacritty.yml', os = 'linux,darwin'}
config_windows = {original = '~/AppData/Roaming/alacritty/alacritty.toml', self_managed = 'CONFIG_ROOT/settings/shells/alacritty/alacritty.toml', os = 'windows'}

[hyper_terminal]
config = {original = '~/.hyper.js', self_managed = 'CONFIG_ROOT/settings/shells/hyper/.hyper.js', os = 'any'}

[wezterminal]
config = {original = '~/.config/wezterm/wezterm.lua', self_managed = 'CONFIG_ROOT/settings/shells/wezterm/wezterm.lua', os = 'any'}

[vtm_windows]
settings = {original = '~/.config/vtm/settings.xml', self_managed = 'CONFIG_ROOT/settings/shells/vtm/settings.xml', os = 'windows'}

[wsl_windows]
config = {original = '~/.wslconfig', self_managed = 'CONFIG_ROOT/settings/wsl/.wslconfig', os = 'windows'}

# [ipython_default_config]
# config = {original = '~/.ipython/profile_default/ipython_config.py', self_managed = 'CONFIG_ROOT/settings/shells/ipy/profiles/default/ipython_config.py'}
# play_extension = {original = '~/.ipython/profile_default/startup/playext.py', self_managed = 'CONFIG_ROOT/settings/shells/ipy/profiles/default/startup/playext.py'}

[mprocs_windows]
config = {original = '~/mprocs.yaml', self_managed = 'CONFIG_ROOT/settings/mprocs/windows/mprocs.yaml', os = 'windows'}

# [tmux_linux]
# config = {original = '~/.tmux.conf', self_managed = 'CONFIG_ROOT/settings/tmux/.tmux.conf'}
# tmate = {original = '~/.tmate.conf', self_managed = 'CONFIG_ROOT/settings/tmux/.tmate.conf'}


[zellij_linux]
config = { original = '~/.config/zellij', self_managed = 'CONFIG_ROOT/settings/zellij' , os = 'linux,darwin'}
#themes = { original = '~/.config/zellij/themes', self_managed = 'CONFIG_ROOT/settings/zellij/themes' }
#layouts = { original = '~/.config/zellij/layouts', self_managed = 'CONFIG_ROOT/settings/zellij/layouts' }


# ===================== IDEs ============================

[zed_linux]
settings = {original = '~/.config/zed/settings.json', self_managed = 'CONFIG_ROOT/settings/zed/settings.json', os = 'linux,darwin'}

[helix]
languages_windows = { original = '~/AppData/Roaming/helix/languages.toml', self_managed = 'CONFIG_ROOT/settings/helix/languages.toml' , os = 'windows'}
config_windows = { original = '~/AppData/Roaming/helix/config.toml', self_managed = 'CONFIG_ROOT/settings/helix/config.toml' , os = 'windows'}
languages_linux = { original = '~/.config/helix/languages.toml', self_managed = 'CONFIG_ROOT/settings/helix/languages.toml' , os = 'linux,darwin'}
config_linux = { original = '~/.config/helix/config.toml', self_managed = 'CONFIG_ROOT/settings/helix/config.toml' , os = 'linux,darwin'}

[lvim]
config_windows = { original = '~/AppData/Local/lvim/config.lua', self_managed = 'CONFIG_ROOT/settings/lvim/windows/config.lua' , os = 'windows'}
config_linux = { original = '~/.config/lvim/config.lua', self_managed = 'CONFIG_ROOT/settings/lvim/linux/config.lua' , os = 'linux,darwin'}


[svim]
init_windows = { original = '~/.SpaceVim.d/init.toml', self_managed = 'CONFIG_ROOT/settings/svim/windows/init.toml' , os = 'windows'}
init_linux = { original = '~/.SpaceVim.d/init.toml', self_managed = 'CONFIG_ROOT/settings/svim/linux/init.toml' , os = 'linux,darwin'}

[linters]
flake8 = {original = '~/.flake8', self_managed = 'CONFIG_ROOT/settings/linters/.flake8', os = 'any'}
# as per https://mypy.readthedocs.io/en/stable/config_file.html
mypy = {original = '~/mypy/config/mypy.ini', self_managed = 'CONFIG_ROOT/settings/linters/.mypy.ini', os = 'any'}
mypy2 = {original = '~/.config/mypy/config', self_managed = 'CONFIG_ROOT/settings/linters/.mypy.ini', os = 'any'}
ruff = {original = '~/.ruff.toml', self_managed = 'CONFIG_ROOT/settings/linters/.ruff.toml', os = 'any'}
pylint = {original = '~/.pylintrc', self_managed = 'CONFIG_ROOT/settings/linters/.pylintrc', os = 'any'}

# ======================= OS ===============================

[apps_windows]
notepadpp = {original = '~/AppData/Local/Microsoft/WindowsApps/notepad++.exe', self_managed = 'C:/Program Files/Notepad++/notepad++.exe', os = 'windows'}
# tesseract = {original = '~/AppData/Local/Microsoft/WindowsApps/tesseract.exe', self_managed = '~/AppData/Local/Tesseract-OCR/tesseract.exe'}  # doesn't work without whole installation dir is on PATH.

[atuin]
config_linux = {original = '~/.config/atuin/config.toml', self_managed = 'CONFIG_ROOT/settings/atuin/config.toml', os = 'linux,darwin'}
themes_linux = {original = '~/.config/atuin/themes', self_managed = 'CONFIG_ROOT/settings/atuin/themes', contents = true, os = 'linux,darwin'}
config_windows = {original = '~/AppData/Roaming/atuin/config.toml', self_managed = 'CONFIG_ROOT/settings/atuin/config.toml', os = 'windows'}
themes_windows = {original = '~/AppData/Roaming/atuin/themes', self_managed = 'CONFIG_ROOT/settings/atuin/themes', contents = true, os = 'windows'}
