
# locations to be backed up to the cloud.
# os can be 'windows', 'linux', 'darwin' or 'any' or comma separated values of the previous values.

[thunderbird]
windows_files = {path_local = '~/AppData/Roaming/Thunderbird/Profiles', path_cloud = '^', encrypt = true, zip = true, rel2home = true, os = 'windows'}
linux_files = {path_local = '~/.thunderbird', path_cloud = '^', encrypt = true, zip = true, rel2home = true, os = 'linux'}


[zoxide]
windows_db = {path_local = '~/AppData/Local/zoxide/db.zo', path_cloud = '^', encrypt = false, zip = false, rel2home = true, os = 'windows'}
linux_db = {path_local = '~/.local/share/zoxide/db.zo', path_cloud = '^', encrypt = false, zip = false, rel2home = true, os = 'linux'}


[atuin]
history = {path_local = '~/.local/share/atuin/history.db', path_cloud = '^', encrypt = true, zip = false, rel2home = true, os = 'any'}


[shell_history]
bash_history = {path_local = '~/.bash_history', path_cloud = '^', encrypt = true, zip = false, rel2home = true, os = 'linux'}
zsh_history = {path_local = '~/.zsh_history', path_cloud = '^', encrypt = true, zip = false, rel2home = true, os = 'darwin'}
pwsh_history = {path_local = '~/AppData/Roaming/Microsoft/Windows/PowerShell/PSReadLine/ConsoleHost_history.txt', path_cloud = '^', encrypt = true, zip = false, rel2home = true, os = 'windows'}


#[dotfiles]
# repo = {path_local = '~/dotfiles', path_cloud = '^', encrypt = true, zip = true, rel2home = true, os = 'any'}


[ipython]
profile = {path_local = '~/.ipython', path_cloud = '^', encrypt = true, zip = true, rel2home = true, os = 'any'}
