
# files to be sources in shell profile

[windows]
files = ['REPO_ROOT/settings/broot/brootcd.ps1',  # defines br command which wraps broot.exe
         'REPO_ROOT/settings/lf/lfcd.ps1',
         'REPO_ROOT/settings/tere/terecd.ps1']

[linux]
files = ['REPO_ROOT/settings/broot/br.sh',
         'REPO_ROOT/settings/lf_linux/exe/lfcd.sh',
         'REPO_ROOT/settings/tere/terecd.sh']

# see broot --install to reinstall and see config files locations.
