
# files to be sources in shell profile

[windows]
files = ['LIBRARY_ROOT/settings/broot/brootcd.ps1',  # defines br command which wraps broot.exe
         'LIBRARY_ROOT/settings/lf/windows/lfcd.ps1',
         'LIBRARY_ROOT/settings/tere/terecd.ps1']

[linux]
files = ['LIBRARY_ROOT/settings/broot/br.sh',
         'LIBRARY_ROOT/settings/lf/linux/exe/lfcd.sh',
         'LIBRARY_ROOT/settings/tere/terecd.sh']

# see broot --install to reinstall and see config files locations.
