[formatting]
line_length = 79

[completion]
copilot = false
activate_on_typing = true

[ai]
inline_tooltip = true
mode = "manual"
rules = ""

[ai.models]
chat_model = "github/gpt-4o-mini"
custom_models = []
displayed_models = []

[package_management]
manager = "uv"

[language_servers.basedpyright]

[language_servers.pylsp]
enabled = true
enable_pydocstyle = false
enable_ruff = true
enable_pyflakes = false
enable_pylint = false
enable_flake8 = false
enable_mypy = true

[language_servers.ty]

[server]
browser = "default"
follow_symlink = false

[runtime]
auto_instantiate = false
auto_reload = "off"
on_cell_change = "autorun"
output_max_bytes = 8000000
reactive_tests = true
default_auto_download = []
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
default_sql_output = "auto"

[display]
dataframes = "rich"
reference_highlighting = false
default_width = "full"
cell_output = "below"
theme = "dark"
default_table_max_columns = 50
code_editor_font_size = 14
default_table_page_size = 10

[mcp]
presets = []

[mcp.mcpServers]

[experimental]

[snippets]
custom_paths = ["/home/alex/code/machineconfig/src/machineconfig/settings/marimo/snippets"]
include_default_snippets = true

[save]
format_on_save = false
autosave = "after_delay"
autosave_delay = 1000

[diagnostics]
sql_linter = true

[keymap]
destructive_delete = true
preset = "default"
