# UNTESTED
[metadata]
name = "bash-history"
description = "A channel to select from your bash history"
requirements = ["bash"]

[source]
command = "awk 'NF { lines[NR] = $0 } END { for (i = NR; i >= 1; i--) { line = lines[i]; if (!(line in seen)) { seen[line] = 1; print line } } }' ${HISTFILE:-${HOME}/.bash_history}"
