
"$schema" = 'https://starship.rs/config-schema.json'
# see https://starship.rs/config/#hostname

add_newline = true

[character]
success_symbol = '[âœ](bold green)'

[username]
style_user = 'red bold'
style_root = 'black bold'
format = 'ğŸ’â€â™‚ï¸[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) @ [$hostname](bold blue) '
disabled = false

[os]
format = "ğŸ–¥ï¸ [$symbol$name $version $codename $edition]($style)"
style = "bold italic bg:dark-blue fg:bright-green"
disabled = false



[os.symbols]
# https://starship.rs/config/#os
Alpine = "ğŸ”ï¸ "
Amazon = "ğŸ™‚ "
Android = "ğŸ¤– "
Arch = "ğŸ—ï¸ "
CentOS = "ğŸ’  "
Debian = "ğŸŒ€ "
Fedora = "ğŸ© "
Linux = "ğŸ§ "
Macos = "ğŸ "
Manjaro = "ğŸ¥­ "
Mint = "ğŸ¸ "
NixOS = "â„ï¸ "
Ubuntu = "ğŸ¯ "
Windows = "ğŸªŸ "

[python]
symbol = 'ğŸ'
pyenv_version_name = false
format ="[((\\($virtualenv\\) ${version})) ${symbol} ${pyenv_prefix}]($style)"

[shell]
bash_indicator = 'ğŸ’²'
powershell_indicator = '>>_'
pwsh_indicator = '>_'
cmd_indicator = 'ğŸªŸ'
nu_indicator = 'ğŸ˜'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false
