
"$schema" = 'https://starship.rs/config-schema.json'
# see https://starship.rs/config/#hostname

add_newline = true

[character]
success_symbol = '[âœ](bold green)'

[username]
style_user = 'red bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) @ [$hostname](bold blue) '
disabled = false

[os]
format = "[$symbol $version $codename $edition]($style)"
style = "bold italic bg:dark-blue fg:bright-green"
disabled = false
# $name


[os.symbols]
# https://starship.rs/config/#os
Android = "îœ"
Arch = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Fedora = "ó°£›"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Mint = "ó°£­"
NixOS = "â„ï¸ "
Windows = "ó°²"
Ubuntu = "ó°•ˆ"

[python]
symbol = 'ğŸ'
pyenv_version_name = false
format ="[((\\($virtualenv\\) ${version})) ${symbol} ${pyenv_prefix}]($style)"

[shell]
# https://www.nerdfonts.com/cheat-sheet
bash_indicator = 'ó±†ƒ'
powershell_indicator = 'î¯‡'
pwsh_indicator = 'îšƒ'
cmd_indicator = 'î¯„'
nu_indicator = 'ó°Ÿ†'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false


[git_branch]
disabled = true
 
[git_commit]
disabled = true
 
[git_state]
disabled = true
 
[git_status]
disabled = true
 
[git_metrics]
disabled = true
