
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'


[username]
style_user = 'red bold'
style_root = 'black bold'
format = 'ğŸ’â€â™‚ï¸[$user]($style) '
disabled = false
show_always = true


[hostname]
# see https://starship.rs/config/#hostname
ssh_only = false
format = '[$ssh_symbol](bold blue) @ [$hostname](bold blue) '
trim_at = '.companyname.com'
disabled = false


[os.symbols]
# https://starship.rs/config/#os
Alpine = "ğŸ”ï¸ "
Amazon = "ğŸ™‚ "
Android = "ğŸ¤– "
Arch = "ğŸ—ï¸ "
CentOS = "ğŸ’  "
Debian = "ğŸŒ€ "
Fedora = "ğŸ© "
Linux = "ğŸ§ "
Macos = "ğŸ "
Manjaro = "ğŸ¥­ "
Mint = "ğŸ¸ "
NixOS = "â„ï¸ "
Ubuntu = "ğŸ¯ "
Windows = "ğŸªŸ "

[os]
format = "ğŸ–¥ï¸ [$symbol$name $version $codename $edition]($style)"
style = "bold italic bg:blue fg:bright-green"
disabled = false

[python]
symbol = 'ğŸ'
pyenv_version_name = false
format ="[((\\($virtualenv\\) ${version})) ${symbol} ${pyenv_prefix}]($style)"
